lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: リンクバル エンジニア採用
description: Linkbal は、テクノロジーで人と人とをつなぎます
github:
- is_project_page: false
